# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'morse_gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(387, 486)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.translateLabel = QtWidgets.QLabel(self.centralwidget)
        self.translateLabel.setGeometry(QtCore.QRect(70, 0, 241, 16))
        self.translateLabel.setObjectName("translateLabel")
        self.morseOutput = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.morseOutput.setGeometry(QtCore.QRect(40, 250, 291, 131))
        self.morseOutput.setReadOnly(True)
        self.morseOutput.setObjectName("morseOutput")
        self.morseLabel = QtWidgets.QLabel(self.centralwidget)
        self.morseLabel.setGeometry(QtCore.QRect(120, 220, 121, 16))
        self.morseLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.morseLabel.setObjectName("morseLabel")
        self.translateButton = QtWidgets.QPushButton(self.centralwidget)
        self.translateButton.setGeometry(QtCore.QRect(140, 170, 75, 23))
        self.translateButton.setObjectName("translateButton")
        self.playButton = QtWidgets.QPushButton(self.centralwidget)
        self.playButton.setGeometry(QtCore.QRect(140, 390, 75, 23))
        self.playButton.setObjectName("playButton")
        self.translateInput = QtWidgets.QTextEdit(self.centralwidget)
        self.translateInput.setGeometry(QtCore.QRect(40, 20, 290, 130))
        self.translateInput.setObjectName("translateInput")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 387, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Morse Code"))
        self.translateLabel.setText(_translate("MainWindow", "Enter Text You Would Like To be Translated Here:"))
        self.morseLabel.setText(_translate("MainWindow", "Translated Morse Code:"))
        self.translateButton.setText(_translate("MainWindow", "Translate"))
        self.playButton.setText(_translate("MainWindow", "Play"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
